version: "3.9"

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "denews"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./app/db/queries/sql:/docker-entrypoint-initdb.d
      # - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - denews

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dayyass@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - denews

  denews_backend:
    container_name: denews_backend
    platform: linux/amd64
    build:      
      dockerfile: dockerfiles/backend.Dockerfile
    volumes:  # TODO: remove
      - ./web3-backend/disputes:/denews/disputes
    ports:
      - "5000:5000"
    networks:
      - denews
    depends_on:
      - postgres

  # denews_frontend:
  #   container_name: denews_frontend
  #   platform: linux/amd64
  #   build:      
  #     dockerfile: dockerfiles/frontend.Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - denews
  #   depends_on:
  #     - denews_backend

  # news_parser:
  #   container_name: news_parser
  #   platform: linux/amd64
  #   build:      
  #     dockerfile: dockerfiles/parser.Dockerfile
  #   ports:
  #     - "5444:5444"
  #   networks:
  #     - denews
  #   depends_on:
  #     - denews_backend

networks:
  denews:
    driver: bridge
